### ISSUE TITLE
Isuues

### ISSUE THREAD

**Issue by ajroxz** [ajroxz/Department_store#1]
issue in receipt 
not able to allign  the data in same order
issue in login 
not able to create a forgot password 
issue in display
not able to deactivate the add button after items in stock becomes 0

**Comment by viplav153** [comment]
hey hi assignme

**Comment by ajroxz** [comment]
issue in receipt
not able to allign the data in same order
issue in login
not able to create a forgot password
issue in display
not able to deactivate the add button after items in stock becomes 0
